### ISSUE TITLE
Add grammar for the EditorConfig-INI file format

### ISSUE THREAD

**Issue by florianb** [jedmao/editorconfig-ini#1]
### Todos

* [ ] Add JSON and TOML grammars as reference
* [ ] Add a third similar grammar as reference
* [ ] Decide for a grammar-format
* [ ] Draft TOC
* [ ] Describe the INI file format entirely

**Comment by jedmao** [comment]
Why are we assimilating JSON and TOML grammars?

Also, how do you propose to make the grammar easier to read than it is right now?

```pest
ini = { SOI ~ (pair | comment)* ~ section* ~ EOI }
WHITESPACE = _{ " " | "\t" }

// section
section = { "[" ~ name ~ "]" ~ body }
name = @{ char+ }
char = { ASCII_ALPHANUMERIC | "." | "_" | "/" | " " }
body = { (NEWLINE ~ (pair | comment)?)* }

// key-value pair
pair = { key ~ "=" ~ value ~ (NEWLINE | EOI) }
key = @{ char+ }
value = @{ (char | "=")* }

comment = { indicator ~ value? ~ (NEWLINE | EOI) }
indicator = { "#" | ";" }
```

**Comment by florianb** [comment]
I think about lending parts of the grammar like f.e. the "exclusion in combination with `ANY`"-pattern if necessary. It might also be interesting to think about the necessity of "escape"-mechanisms. But i am still thinking about the different use-patterns and if there may raise any conflicts in parsing.

The grammar is already pretty readable. At the end when the grammar supports everything we want, i'd propose some changes like substituting single-use-references by there values and so on.
